### ISSUE TITLE
clear-10000-containers.img.xz 404

### ISSUE THREAD

**Issue by dcalvom** [clearcontainers/cc-dirtycow-demo#1]
Hi,

It seems this file is not available anymore. Any idea where I could get it to test the demo?

**Comment by johnandersen777** [comment]
@dcalvom This is a Clear Linux project thing, they had to reclaim space on their servers so they deleted that old image. The reason we have to use that one is because it is a pre-dirtycow patch one therefore it can be exploited. We exploit it with this demo code and show that it doesn't give an attacker access to the host.

I'm going to add that to the release binaries if possible so that it stays here forever. I'll let you know when its updated to use the one hosted here.

> Saw on your profile you're location is Costa Rica, I just got back from there!
> :costa_rica: Pura Vida!

**Comment by dcalvom** [comment]
Thanks, @pdxjohnny!

I appreciate your help!

> Haha, that's cool! I hope you enjoyed your trip!. We will be more than happy of having you back! Come back soon! :v:

**Comment by johnandersen777** [comment]
@dcalvom Let me know if that works. The setup script used to work on a bare minimal Ubuntu 16.04.1 box but I haven't tried it in a while. Technically https://github.com/clearcontainers/cc-dirtycow-demo/commit/df60f3ae92d3adeecbe607b669eef897e49a4a82 fixes this issue's title so just make another one if something else goes wrong. I'm always happy to help.

**Comment by dcalvom** [comment]
You rock @pdxjohnny thanks!!!

**Comment by johnandersen777** [comment]
Pura Vida man I hope you get shells! 😀

On Jul 11, 2017 8:06 AM, "Daniel Calvo Marin" <notifications@github.com>
wrote:

You rock @pdxjohnny <https://github.com/pdxjohnny> thanks!!!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/clearcontainers/cc-dirtycow-demo/issues/1#issuecomment-314474626>,
or mute the thread
